#page title
page_title                                : Productivity Card                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1476660150                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.ramenstartup.productivity_card                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Productivity Card                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Maximize your productivity and fulfillment throughout your day.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Charles Han
your_link                                 : https://charleshan.com
your_city                                 : Vancouver, Canada.
email_address                             :
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : CharlesHanCOM
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Get More Done
    description                           : Based on Marc Andreessen's Daily To-Do and Anti-Todo list.
    fontawesome_icon_name                 : rocket
    
  - title                                 : Daily To-Do
    description                           : “It makes you feel more accomplished.”
    fontawesome_icon_name                 : list-alt

  - title                                 : Anti To-Do
    description                           : “It gives you insight into your work patterns.”
    fontawesome_icon_name                 : check-square

  - title                                 : Reminders
    description                           : “It helps you build good habits.”
    fontawesome_icon_name                 : bell

  - title                                 : Be Energized
    description                           : “You get that little rush of endorphins.”
    fontawesome_icon_name                 : fire

  - title                                 : Review and Repeat
    description                           : “At the end of the day, marvel at all the things you got done and prepare 3 to 5 tasks for next day.”
    fontawesome_icon_name                 : sync-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : https://ph-files.imgix.net/52d46f34-fe6a-4f67-bdf7-4351c12a4296                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
